# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 95f4c41
_src_path: gh:astrojuanlu/copier-pylib
author_email: hello@juanlu.space
author_name: Juan Luis Cano Rodríguez
github_org: astrojuanlu
package_name: pygetimportables
project_name: pygetimportables
short_description: Python functions to get top-level importable names
